// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub fn transfers(n: u32,) -> _rt::Vec::<(u32,i32,)>{
  unsafe {

    #[cfg_attr(target_pointer_width="64", repr(align(8)))]
    #[cfg_attr(target_pointer_width="32", repr(align(4)))]
    struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    unsafe extern "C" {
      #[link_name = "transfers"]
      fn wit_import1(_: i32, _: *mut u8, );
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ){ unreachable!() }
    wit_import1(_rt::as_i32(&n), ptr0);
    let l2 = *ptr0.add(0).cast::<*mut u8>();
    let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base6 = l2;
    let len6 = l3;
    let mut result6 = _rt::Vec::with_capacity(len6);
    for i in 0..len6 {
      let base = base6.add(i * 8);
      let e6 = {
        let l4 = *base.add(0).cast::<i32>();
        let l5 = *base.add(4).cast::<i32>();

        (l4 as u32, l5)
      };
      result6.push(e6);
    }
    _rt::cabi_dealloc(base6, len6 * 8, 4);
    let result7 = result6;
    result7
  }
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub fn device() -> u32{
  unsafe {

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    unsafe extern "C" {
      #[link_name = "device"]
      fn wit_import0() -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn wit_import0() -> i32{ unreachable!() }
    let ret = wit_import0();
    ret as u32
  }
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub fn device_handle() -> u32{
  unsafe {

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    unsafe extern "C" {
      #[link_name = "device-handle"]
      fn wit_import0() -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn wit_import0() -> i32{ unreachable!() }
    let ret = wit_import0();
    ret as u32
  }
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub fn frame_stream() -> u32{
  unsafe {

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    unsafe extern "C" {
      #[link_name = "frame-stream"]
      fn wit_import0() -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn wit_import0() -> i32{ unreachable!() }
    let ret = wit_import0();
    ret as u32
  }
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub fn object_detector() -> u32{
  unsafe {

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    unsafe extern "C" {
      #[link_name = "object-detector"]
      fn wit_import0() -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn wit_import0() -> i32{ unreachable!() }
    let ret = wit_import0();
    ret as u32
  }
}
#[allow(unused_unsafe, clippy::all)]
#[allow(async_fn_in_trait)]
pub fn renderer(rep: u32,) -> u32{
  unsafe {

    #[cfg(target_arch = "wasm32")]
    #[link(wasm_import_module = "$root")]
    unsafe extern "C" {
      #[link_name = "renderer"]
      fn wit_import0(_: i32, ) -> i32;
    }

    #[cfg(not(target_arch = "wasm32"))]
    unsafe extern "C" fn wit_import0(_: i32, ) -> i32{ unreachable!() }
    let ret = wit_import0(_rt::as_i32(&rep));
    ret as u32
  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {

  #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
  pub mod usb {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() =
    super::super::__link_custom_section_describing_imports;
    
    use super::super::_rt;
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_start_cabi<T: Guest>() { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();{
      T::start()
    };
  } }
  pub trait Guest {
    #[allow(async_fn_in_trait)]
    fn start() -> ();
  }
  #[doc(hidden)]

  macro_rules! __export_usb_cabi{
    ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

      #[unsafe(export_name = "usb#start")]
      unsafe extern "C" fn export_start() {
        unsafe { $($path_to_types)*::_export_start_cabi::<$ty>() }
      }
    };);
  }
  #[doc(hidden)]
  pub(crate) use __export_usb_cabi;

}

}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::vec::Vec;

  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_host_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::usb::__export_usb_cabi!($ty with_types_in $($path_to_types_root)*::exports::usb);
  )
}
#[doc(inline)]
pub(crate) use __export_host_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:component:usb:host:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 302] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb3\x01\x01A\x02\x01\
A\x0d\x01o\x02yz\x01p\0\x01@\x01\x01ny\0\x01\x03\0\x09transfers\x01\x02\x01@\0\0\
y\x03\0\x06device\x01\x03\x03\0\x0ddevice-handle\x01\x03\x03\0\x0cframe-stream\x01\
\x03\x03\0\x0fobject-detector\x01\x03\x01@\x01\x03repy\0y\x03\0\x08renderer\x01\x04\
\x01B\x02\x01@\0\x01\0\x04\0\x05start\x01\0\x04\0\x03usb\x05\x05\x04\0\x12compon\
ent:usb/host\x04\0\x0b\x0a\x01\0\x04host\x03\0\0\0G\x09producers\x01\x0cprocesse\
d-by\x02\x0dwit-component\x070.230.0\x10wit-bindgen-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

